version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - OlegRa
  ignore:
  - dependency-name: Alpaca.Markets
    versions:
    - "> 5.0.3-alpha3"
  - dependency-name: Alpaca.Markets
    versions:
    - 5.0.0-alpha3
    - 5.0.1-alpha2
    - 5.0.1-alpha3
    - 5.0.1-alpha4
    - 5.0.3-alpha2
  - dependency-name: docfx.console
    versions:
    - 2.56.7
    - 2.57.0
    - 2.57.1
    - 2.57.2
  - dependency-name: JetBrains.Annotations
    versions:
    - 2021.1.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
